source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-param'
gem 'sinatra-contrib'
gem 'rack-contrib'
gem 'shotgun'
gem 'dotenv'
gem 'mongoid', '>=5.0.2'
gem 'carrierwave-mongoid', '>=0.8.0'
gem 'mongoid-enum'
gem 'sinatra-initializers'
gem 'active_model_serializers'
gem 'mini_magick'
gem 'sidekiq'